import React from "react";

interface SnackListProps {
  content: string;
}

const SnackList: React.FC<SnackListProps> = ({ content }) => {
  const formattedContent = content.replace(
    /\*\*(.*?)\*\*/g,
    "<strong>$1</strong>"
  );

  const paragraphs = formattedContent.split(/\n\n+/).filter(Boolean); // Split by double newlines

  return (
    <div className="space-y-4 rounded-sm bg-slate-200 p-6">
      <h2 className="text-black font-extrabold text-xl">Generated Summary</h2>
      {paragraphs.map((paragraph, index) => {
        if (paragraph.match(/\d\.\s+/)) {
          const items = paragraph.split(/\d\.\s+/).filter(Boolean);
          return (
            <ul key={index} className="list-disc list-inside pl-4">
              {items.map((item, itemIndex) => (
                <li
                  key={itemIndex}
                  className="text-black"
                  dangerouslySetInnerHTML={{ __html: item }}
                />
              ))}
            </ul>
          );
        } else {
          return (
            <p
              key={index}
              className="text-black"
              dangerouslySetInnerHTML={{ __html: paragraph }}
            />
          );
        }
      })}
      <div className="bg-blue-50 border-l-4 border-blue-400 p-4 my-4 text-sm text-blue-700">
        <p className="font-semibold">Disclaimer:</p>
        <p className="mt-2">
          The following summary has been generated by a Language Model (LLM).
          While we strive for accuracy, please be aware that there may be errors
          or omissions. For critical decisions, it is recommended to verify the
          information with a reliable source.
        </p>
      </div>
    </div>
  );
};

export default SnackList;
